name: CI
on:
  schedule:
    - cron: "30 * * * *"
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Update database
        run: |
          python main.py --create
          python main.py --update
      - name: Add to git
        run: |
          git config --local user.email "tiankaima@163.com"
          git config --local user.name "ACTION FROM BOT"
          git add storage.db -f
          git commit -m "Update database"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: build
  Sync:
    runs-on: ubuntu-latest
    needs: Update
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
                    cd ~/ASoul-Comment
                    git fetch --all
                    git reset --hard origin/master
                    git pull
                    git checkout build
                    python -m pip install -U pip
                    python -m pip install -r requirements.txt
                    nohup python -m uvicorn server:server &
                    exit