name: CI
on:
  schedule:
    - cron: "15 * * * *"
  push:
    branches: [ master ]
  workflow_dispatch:


jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt
      - name: Update database
        run: |
          mkdir logs
          python main.py --update-all
      - name: Add to git
        run: |
          git config --local user.email "tiankaima@163.com"
          git config --local user.name "ACTION FROM BOT"
          git add storage.db
          git commit -m "Update database"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: build
